// Generated by CoffeeScript 1.6.2
(function() {
  var exports, search,
    _this = this;

  exports = this;

  exports.ACCESS_TOKEN = "ac03071e08039517fc014ac9f47ad28e439447d3";

  exports.API_ADDRESS = "https://api-ssl.bitly.com";

  exports.search = search = function(query) {
    var resultData, route;

    resultData = "";
    route = "/v3/search/";
    return ($.ajax(API_ADDRESS + "/v3/search", {
      type: 'GET',
      dataType: 'html',
      async: false,
      data: {
        access_token: ACCESS_TOKEN,
        q: query
      }
    })).responseText;
  };

}).call(this);
